version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: compia_db
    restart: always
    environment:
      POSTGRES_USER: compia_user
      POSTGRES_PASSWORD: compia_password
      POSTGRES_DB: compia_editora
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
